### ISSUE TITLE
Parallelism in mamba

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#100]
These days `conda` attempts to solve reduced problems at a various stages before falling back to a full solve. The idea being that if a quick solve works then you're much better off.

When it doesn't though it can be several multiples *worse* than just doing the full solve straight away:
https://github.com/conda/conda/issues/9309

Does `mamba` also have this functionality? I think I remember seeing somewhere that it doesn't because the full solve isn't the bottleneck.

If however it does use multiple solves, a *very* low hanging fruit would be to run them in parallel.

**Comment by dhirschfeld** [comment]
:100:

**Comment by wolfv** [comment]
we're currently always running on the full index and it's not really the bottleneck at least for small-ish environments.
I have explored using the reduced repodata. I think the main benefit would be in smaller download sizes for the repodata vs. downloading the full repodata everytime.

I think parallel solves would be very interesting for situations where conda-build is involved (there one usually has many solves over the same repodata).

**Comment by dhirschfeld** [comment]
I'll close then as answered!

**Comment by wolfv** [comment]
Let's keep this open as I have been thinking a little further on how & what to parallelize in mamba.

We basically have three phases:

Before solve

We can in parallel download repodata -> unpack repodata (it comes as tar.bz2) -> then parse repodata, and clean trash (compare #103)

So we have N repodata tasks with 3 subtasks (and might need a mutex during parsing), and we have one clean trash. 

Then we have the solver phase

And then we can parallely download -> extract packages -> link packages 

However, for the linking the order needs to be correct otherwise post link steps might not work.

I think this would map well on a task based parallelism framework such as cpp-taskflow:

https://github.com/cpp-taskflow/cpp-taskflow

But I am also afraid that it might be "overkill".

Another good option might be to use a thread pool. There is a very simple implementation here: https://github.com/progschj/ThreadPool/blob/master/ThreadPool.h

which we could use & adapt. If we have a queue of tasks that get added to the threadpool queue that might be as good as using the more complicated task pool :)

**Comment by xhochy** [comment]
For the thread pool, we have a quite well-tested implementation in https://github.com/apache/arrow/blob/master/cpp/src/arrow/util/thread_pool.h Might be useful if you come across cross-platform issues.
