### ISSUE TITLE
Installing mamba when base env is read-only

### ISSUE THREAD

**Issue by thomasaarholt** [mamba-org/mamba#1056]
I'm using Anaconda provided on a supercomputer using the `mload` system. The system provides anaconda ready to use, but the `base` environment is in a read-only location. We are supposed to create new environments on our home directories and install whatever we need there. Hence I cannot install `mamba` in `base`.

Is there an appropriate way to install mamba in this situation? I've tried emulating `base` by creating a `base2` and installing mamba there, but subsequent environments (e.g. `myenv`) created with mamba then default to `~/.conda/envs/base2/envs/myenv`, which is outside the search path of `conda activate`.

One alternative is to install `miniconda` or `mambaforge` and just use that, so I guess I am just curious.

**Comment by wolfv** [comment]
Did you already talk to your sysadmin? I think that's the easiest route. 

The main problem is that you'll install a copy of conda when you install mamba (since mamba depends on conda). And then that new conda will be used by mamba, which puts the base prefix at a different location.

We could do some tricks with settings the pkgs_dirs / envs_dirs directly to the place of the read-only base installation but I think we'd need to do some work on the mamba side to make that clean.

**Comment by thomasaarholt** [comment]
That's fine. I was mainly checking to see if there was something obvious I was missing.

The main reason for not asking sysadmin about it is that I don't want to give me more technical debt. I've had to ask them to update conda a few times already. That said, I guess asking them to update conda and mamba at the same time isn't a huge ask.
