### ISSUE TITLE
Mamba claims nothing provides a package that is required by something explicitly excluded by a pin

### ISSUE THREAD

**Issue by IanSudbery** [mamba-org/mamba#1145]
I am trying to install an environment from a yml file ([attached](https://github.com/mamba-org/mamba/files/7061506/cgat-flow-pipelines.yml.txt)), part of this yml pins the `r-base` channel to >=3.5. However on trying to create the environment I get the error message from mamba:

```
Encountered problems while solving:
  - nothing provides icu 54.* needed by r-base-3.3.1-1
```

What is happening here? Is mamba trying to sovle with r-base-3.3.1 (even though the pins force r-base>=3.5) or is the error message mistaken?

Output of mamba info:
```
     active environment : None
       user config file : /home/XXXX/.condarc
 populated config files : /home/XXXX/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.1.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /shared/sudlab1/General/apps/conda/conda-install  (writable)
      conda av data dir : /shared/sudlab1/General/apps/conda/conda-install/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /shared/sudlab1/General/apps/conda/conda-install/pkgs
       envs directories : /data/XXXX/cgat/envs
                          /shared/sudlab1/General/apps/conda/conda-install/envs
                          /home/XXXX/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.24.0 CPython/3.8.1 Linux/3.10.0-1160.36.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 28002:5300
             netrc file : None
           offline mode : False
```

**Comment by petacube** [comment]
@IanSudbery  my feeling, since nobody had replied to your question, is conda repos are all messed and nobody maintains them propertly and probably better to install from pip/cran repos rather than use conda/mamba

**Comment by farshadf** [comment]
This is really frustrating to not see any update. I am wondering if there is anybody from the conda/mamba team to attend to these issues. A short update would be very useful.

**Comment by joshdunnlime** [comment]
Did you, like me, run:

```mamaba create -n name -f enironmant.yml```

and not

```mamba env create -n name -f environment.yml```

by any chance?

**Comment by mfansler** [comment]
I've also come across this frequently. It possibly indicates that pruning from particular rules happens later than is necessary. So, potential room for optimization, but I wouldn't consider it an error.

The pattern that I see come up repeatedly is that when an environment cannot be solved, Mamba will report the last considered case. And since the solver appears to work from newest to oldest, this can lead to super old versions of excluded packages turning up **as dependencies of other packages**. So, it isn't that it would ever install R 3.3; only that the solver was running through the DAG of a different requirement and reached a stopping point **prior to applying the `r-base>3.5` rule**. Unfortunately, this particular environment is so huge that pinpointing the conflict(s) would be tedious.

I think the main issue here is that **there is major room for improvement in conflict reporting**.

---

@petacube seems a rather pessimistic take. Giving precise blame messaging for why the solver fails is difficult. It's not that the SAT solver is resulting in incorrect solves, rather that it's not always good at describing *why* a particular combination of requirements cannot be satisfied. This is why it is crucial that environment distributors report both the solved environments they have successfully worked with (`conda env export` and `conda list --canonical`) as well as a version intended for reuse (`conda env export --from-history`).

The particular environment YAML that @IanSudbery is attempting to install is an example of bad practice, in my opinion. Users should not be building such monolithic environments that try to pack multiple major components (Python + R + Perl + Jupyter + bioinfo tools) in one environment. It's the same reason why Anaconda distribution has such a terrible reputation for aging poorly. Balancing hundreds of dependencies is a nasty problem and just because Mamba has vastly expanded the capacity for solving large environments shouldn't be seen as a pass for environment designers to be careless.

---

For this particular YAML, the combination of `pysam==0.15.2` and `cgat-apps >=0.6.4` seems like an issue. That `pysam` build locks in `samtools=1.9` which in turn leads to `htslib=1.9`, but the lowest `cgat-apps` all start with `htslib>=1.12,<1.13`.  That is, I can't even solve the simple combination:

```bash
$ mamba create -n foo pysam'==0.15.2' cgat-apps'>=0.6.4'

Looking for: ['pysam==0.15.2', "cgat-apps[version='>=0.6.4']"]

conda-forge/noarch                                          Using cache
bioconda/noarch                                             Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/noarch                                               Using cache
pkgs/main/linux-64                                            No change
pkgs/r/linux-64                                               No change
conda-forge/linux-64                                          No change
bioconda/linux-64                                             No change
Encountered problems while solving:
  - package cgat-apps-0.6.4-py38hc5b2f15_0 requires htslib >=1.12,<1.13.0a0, but none of the providers can be installed
```

**Comment by zoltanmaric** [comment]
I ran into this issue while attempting to build a docker image.

Because I'm working on a MacBook Air with an **M1 processor** (which is an arm64 architecture), **docker will by default pull linux-based images for the arm64 architecture (called `aarch64`)**, whereas on Intel processors it would presumably pull `x86_64` images.

In this case, my issue was that a conda package I was trying to install (`pyomo`) was indeed not available for the `linux/aarch64` platform, so mamba was right.

The solution was to explicitly require the image for the `x86_64` platform in my `Dockerfile`:
```Dockerfile
FROM --platform=linux/x86_64 mambaorg/micromamba
```

After this, `pyomo` installed successfully, because it was available for the `linux/x86_64` architecture.

---

Of course the real solution to this problem is to have `pyomo` conda package also built for the `linux/aarch64` platform. This may be a good starting point to do that: https://github.com/jjhelmus/conda4aarch64

**Comment by jonashaag** [comment]
Better use this as a starting point: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/osx_arm64.txt

**Comment by jvivian-atreca** [comment]
> In my case the problem was that the package I was trying to install was indeed not available for the architecture I was trying to install it on (`aarch64`). I ran into it while attempting to build a docker image.
> 
> Because I'm working on a MacBook Air with an **M1 processor** (which is an arm64 architecture), **docker will by default pull linux-based images for the arm64 architecture (called `aarch64`)**, whereas on Intel processors it would presumably pull `x86_64` images.
> 
> In this case, my issue was that a conda package I was trying to install (`pyomo`) was indeed not available for the `linux/aarch64` platform, so mamba was right.
> 
> The solution was to explicitly require the image for the `x86_64` platform in my `Dockerfile`:
> 
> ```dockerfile
> FROM --platform=linux/x86_64 mambaorg/micromamba
> ```
> 
> After this, `pyomo` installed successfully, because it was available for the `linux/x86_64` architecture.
> 
> Of course the real solution to this problem is to have `pyomo` conda package also built for the `linux/aarch64` platform. This may be a good starting point to do that: https://github.com/jjhelmus/conda4aarch64

Thank you for this solution — I ran into a similar problem trying to build `polars` in a `micromamba` container.

**Comment by JohanMabille** [comment]
This is not a mamba issue but rather a missing package. An issue should be opened on the appropriate package repository or project.
