### ISSUE TITLE
solver does not handle meta-packages

### ISSUE THREAD

**Issue by soumith** [mamba-org/mamba#1223]
The following commands install the incorrect `habitat-sim` package if `mamba` is used. When `conda` is used, it handles things correctly.

```
conda create -n habitat2 python==3.7 habitat-sim headless -c aihabitat -c conda-forge
```

Correctly installs `aihabitat/linux-64::habitat-sim-0.2.1-py3.7_headless_linux_fc7fb11ccec407753a73ab810d1dbb5f57d0f9b9`

```
mamba install habitat-sim headless -c aihabitat
```

Incorrectly installs `py3.7_linux_fc7fb11ccec407753a73ab810d1dbb5f57d0f9b9`

Installing the metapackage `headless` is supposed to change which binary of `habitat-sim` gets installed (as you see in the conda command).

**Comment by wolfv** [comment]
Hi @soumith

yeah that is unfortunate. I just checked the `repodata.json` of the `aihabitat` channel at `https://conda.anaconda.org/aihabitat/linux-64/repodata.json` and it seems that it's using `features` and `track_features` to decide between the two variants.

Unfortunately `track_features` have been deprecated since a while and we haven't implemented full support for them in mamba (they are still used, but only to down-weight variants). In conda-forge and defaults channel, only `mutex` packages are used these days. 

`pytorch` has now also adopted `mutex` packages: #336

**Comment by wolfv** [comment]
More info on mutex packages: https://docs.google.com/document/d/1S2D4lTYfDV4GNGbRSDWobH2PWilUVXTHRgl-2tnzdxY
