### ISSUE TITLE
Solving issues due to python pin

### ISSUE THREAD

**Issue by shevelevs** [mamba-org/mamba#1245]
It seems that here https://github.com/mamba-org/mamba/blob/bff16c2bdc4103ba74c23ab4fdbf58849a55981c/mamba/mamba/mamba_env.py#L64 mamba pins python version found in current environment.

The issue we are seeing because of that is that solving operation becomes order-dependent.

Say, there's a package p1 that has dependency on python (without constraint). Installing this package first will result in the latest available version of python (say, 3.9) in the environment. Now let's say I then want to install package p2 which has python version constraint, say <=3.8. Now when I try to install p2 into the environment that has p1, solving will fail, because python version is pinned. Not that installing both p1 and p2 as a part of the same transaction or in a different order (p2, then p1) will not result in failure.

Any opinion/advise wrt this behavior? Why is there a need to pin python even if original requirement didn't have the pin?

**Comment by wolfv** [comment]
In a regular usage, a user will start out with some version of python in a fresh environment. Then the user will maybe install some additional packages with mamba/conda. At some point, the user might also install some packages with `pip`.

Now the packages installed with `pip` end up in the `lib/python3.8/site-packages` directory. 

Updating or accidentally updating the `python` package would mean that the user would "loose" all `pip` installed packages. That's why the python version is pinned, as for most users that's the better understandable and desired behavior I'd say. In fact, we should probably do the same for ruby and some other language packages where people might mix&match with the language specific package manager.

**Comment by wolfv** [comment]
With `micromamba` you can use `--no-py-pin` or configure `no_py_pin: true` in the `.condarc` file.

**Comment by qysnn** [comment]
> With `micromamba` you can use `--no-py-pin` or configure `no_py_pin: true` in the `.condarc` file.

It seems `mamba` cannot do that as it shows `mamba: error: unrecognized arguments: --no-py-pin`. Is there anyway to get around the python pin with `mamba`?
