### ISSUE TITLE
libmamba's filelock fails on filesystems that do not support F_WRLCK

### ISSUE THREAD

**Issue by meson800** [mamba-org/mamba#1446]
Synopsis
----------
Programs using libmamba's filelock (e.g. `micromamba` and recent versions of mamba past when #1238 merged) fail when run on filesystems that do not support F_WRLCK, unlike `conda` and older versions of `mamba`.

Which filesystems don't support `F_WRLCK`? I use mamba on a shared computing cluster, where the main filesystem is a networked filesystem that I don't control (fstab entry: `type lustre (rw,noflock,lazystatfs)`) which has locking disabled. There is a node-local filesystem that supports locking, but the quotas on the local filesystem are too small to support a package cache (e.g. you run out of space on the node-local filesystem when trying to install a decently-sized environment).

It looks like [Conda's lock](https://github.com/conda/conda/blob/master/conda/lock.py#L55) is quite simple. Is it feasible to have a fallback in case `fcntl` returns `ENOSYS` (function not implemented) that tries to spin-lock like Conda? I can try my hand at a PR if there isn't a better solution.

Reproduction steps
----------------------
1. Be on a filesystem with locks disabled (not sure how to reproduce this 😢, perhaps with some shared-library injection hacking I could have a local testcase)
2. Make sure the root directory is set to.
3. Start any operation that tries to open the package cache (such as `micromamba create -p ./test python -c conda-forge`)
4. Get LockFile error `Could not set lock (Function not implemented)`

An example `strace` log looks like this
```
openat(AT_FDCWD, "/path/to/this/filesystem/micromamba/pkgs/cache/cache.lock", O_RDWR|O_CREAT, 0666) = 7
getpid()                                = 11367
lseek(7, 0, SEEK_SET)                   = 0
read(7, "", 20)                         = 0
fcntl(7, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=21, l_len=1}) = -1 ENOSYS (Function not implemented)
clock_gettime(CLOCK_REALTIME, {tv_sec=1643927299, tv_nsec=895008863}) = 0
write(2, "error   ", 8error   )                 = 8
write(2, " Could not set lock (Function no"..., 47 Could not set lock (Function not implemented)
) = 47
```

**Comment by wolfv** [comment]
Hi @meson800 thanks for the detailed analysis. I am not sure wether it's worth it to implement another file locking mechanism or to just disable file locking (maybe with a warning?).

In any case, a PR would be very much appreciated!

**Comment by meson800** [comment]
I'm testing out doing the simplest thing, effectively checking if the lockfile initially existed in the case where we get `ENOSYS`. The lock is considered successful if the file did not exist when we created it (e.g. we were the ones to create it).

On the filesystem without locking, the alternate strategy appears to work. Starting two processes simultaneously will do the right thing, with the first process to the lock printing just the warning message:
```
warning  File locking unimplemented on this filesystem. Using alternate locking strategy
```
with the other one printing errors:
```
warning  Cannot lock 'test/conda-meta'
    Waiting for other mamba process to finish
warning  File locking unimplemented on this filesystem. Using alternate locking strategy
error    Could not set lock (Function not implemented)
error    LockFile can't be set at 'test/conda-meta'
    This could be fixed by changing the locks' timeout or cleaning your environment from previous runs
critical LockFile error. Aborting.
```

Remaining todos/questions:
1. I believe I can write test cases for this using LD_PRELOAD, basically make a wrapper that we can preload and override `fcntl` to return `ENOSYS` on-demand within the test case.
2. There is technically still a race condition in the constructor of the LockFile because [fs::exists](https://github.com/mamba-org/mamba/blob/master/libmamba/src/core/util.cpp#L800) is called to set `m_lockfile_existed`, and then we open it later. Another process could potentially create the lockfile after the existence check but before we open it. Opening with `O_EXCL` would atomically check for file existence/creation, but fails if the file already exists, which is undesirable here.  What is the use case for letting the LockFile constructor open an already-existing lockfile?
3. Currently [is_locked](https://github.com/mamba-org/mamba/blob/master/libmamba/src/core/util.cpp#L949) does not check the return value of `fcntl`, so if `fcntl` fails for any reason, it skips the locking step entirely (e.g. just checks that lockfile PID == our PID). I can update this to also check for `ENOSYS` and use file-existence as a proxy for locking as well.
4. Is there a already in-use way to only print warning messages once as needed? Right now my warning message gets a little spammy, printing once per lock held.

**Comment by aghr** [comment]
Dear Mamba Team, 

I ran into the same issue working with conda&mamba on a HPC with special file system for fast handling of big files called lustre. On this file system mamba 0.22.1 still works, but mamba 0.24.0 throws errors that files could not be locked. 

Talking to our sys admin I am under the impression that one solution could be have one option to switch off file locking preventing mamba running into this issue. He says that other software systems like PostgreSQL have the same issue and it's a petty that they don't have such an option because we cannot use them on our HPC file system. This option to switch off file locking should be settable by the user through some sort of configuration of mamba like users can do for conda via .condarc. 

I deem a solution to this issue in future mamba versions extremely important, as other systems like Snakemake, which we use for the implementation of our scientific workflows, use mamba in the background to install conda environments. As such, I can run our Snakemake workflows right now only with previous mamba versions. Given the popularity of Snakemake and Conda/Mamba in the scientific community I expect this issue to have quite an impact on this community.

Many thanks.
Andre

**Comment by aghr** [comment]
Dear Christopher (meson800), Maybe there is a misunderstanding. Our sys admin says that PostgreSQL has issues with file locks too on some file systems like the current version of Mamba. He says that this is a pity hampering our work with PostgreSQL and that PostgreSQL should (but still hasn't) an option to let the user decide if s/he wants to use this file-lock feature or work without it, which would be still quite save if eg. it's only one user who works with the PostgreSQL DB.

Looking forward to your contribution in solving this issue. Let me know if I can help, eg. trying your fix and see if it's working on our HPC system.

Andre

**Comment by danpf** [comment]
@aghr 
I have a PR #1830 , do you think you could try it on your filesystem?
It seems to be working on mine.

you can disable locking by setting the environment variable `MAMBA_DISABLE_LOCKFILE=TRUE` or by setting `disable_lockfile: true` in your .condarc or .mambarc

**Comment by aghr** [comment]
@danpf 
I tried but got stuck with the installation. The issue might be a confusion between mamba installed in my conda env and the mamba from your branch. Here is what I did, could you please say if this is the right way, at least in principle. Many thanks.
1. Clone https://github.com/danpf/mamba/tree/danpf-nolock
2. Switch to danpf-nolock
3. Follow instructions for a local dev environment on https://mamba.readthedocs.io/en/latest/developer_zone/build_locally.html#

I do all this in an env where Mamba is installed to follow the second step of 3. which is mamba env update --name <env_name> --file ./<project>/environment-dev.yml

Doing all this, then calling mamba I'll use the original one installed already in the conda env. To use the developed version I'd use something along: python /home/XXXXXX/testmamba/mamba/mamba/mamba/mamba.py , but running this libmamba.so.2 complains about a missing shared object file.

**Comment by danpf** [comment]
> python /home/XXXXXX/testmamba/mamba/mamba/mamba/mamba.py 

wow that's a lot of mamba!

I was able to install it with the following commands:

```
# while in ./build
cmake .. \
    -DBUILD_LIBMAMBA=ON \
    -DBUILD_SHARED=ON \
    -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
    -DBUILD_LIBMAMBAPY=ON -GNinja
ninja
ninja install
pip install -e ../mamba --no-deps
pip install -e ../libmambapy --no-deps
```
I don't know which directions you're following, but when I built this way my build/libmamba/libmamba.so.2 was dynamically linked to my build/libmambapy/bindings.cpython-310-x86_64-linux-gnu.so file.

you need to do `ninja install` (or make install if you're just using make) to mke sure that the bindings...so file is put into your environment correctly

**Comment by aghr** [comment]
@danpf 
Many thanks. Following your commands 1-by-1 I could install mamba.

I wanted to apply it to create an environment with package CellXGene to be installed but I still see errors related to file locks. I'll attach a text file with the errors or paste it here.

One thing I am not sure about is if the new mamba indeed used the new libmamba or not. If not than I'd say the errors I still see come from the fact that the old libmamba was used. Actually, I struggled (with our admin) to get the new mamba working: I have mambaforge installed with other versions of mamba and libmamba, I'd guess. Conda init which happens during login via some lines added to the .bashrc defines functions conda and mamba I couldn't get our system to use the new mamba; changing PATH didn't help...still the mamba from mambaforge was used. I ended up removing the conda-init lines from my .bachrc, re-login into the shell, extended PATH to contain the bin of my testmamba installation, with that mamba (new version) run mamba init, re-login to the shell and trying to create a environment: mamba create -n test -c bioconda cellxgene . From the version of mamba 0.25.0 I see it is the new one as the mamba from my mambaforge installation (which I had silenced by changing by .bashrc) is of version 0.22.0., 

I am not sure of that way is the right way to try your new mamba version. I couldn't find another way. As I still see errors related to file locks but you have extended mamba to cope with this kind of issue I am not sure if ..maybe there is still some older version of libmamba lingering around on our system which is used instead of the new libmamba that came with your fix.

I can try more ...but I'd need more guidance how to configure my system on our cluster to use the mamba from your fix. 

Many thanks.

Andre

**Comment by danpf** [comment]
Hi @aghr  sorry for not responding earlier -- got distracted. 

I am not sure what could be wrong here.

to make sure you don't have conflicting environments maybe try this.

1. remove the mamba init part of your .zshrc
2. make sure that there is no mamba in your environment via `which -a mamba`
3. create a new mamba environment directory like `mkdir $HOME/matest && export MAMBA_ROOT_PREFIX=$HOME/matest && CONDA_PREFIX=$HOME/matest`
4. create a temporary directory to hold a micromamba binary (we do this to make sure when we install mamba we don't have a conflicting  mamba) `mkdir $HOME/bin`
5. download micromamba follow instructions at https://mamba.readthedocs.io/en/latest/installation.html#manual-installation (`cd $HOME` first)
6. add bin dir to path `export PATH=$HOME/bin:$PATH`
7. init micromamba follow the rest of the instructions at https://mamba.readthedocs.io/en/latest/installation.html#manual-installation
8. `git clone https://github.com/danpf/mamba.git && cd mamba && git checkout danpf-nolock && mkdir build && cd build`
9.  `micromamba install --name mamba-dev --file ../mamba/environment-dev.yml`
10. `micromamba activate mamba-dev`
11. run:
```
cmake .. \
    -DBUILD_LIBMAMBA=ON \
    -DBUILD_SHARED=ON \
    -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX \
    -DBUILD_LIBMAMBAPY=ON -GNinja
ninja
ninja install
pip install -e ../mamba --no-deps
pip install -e ../libmambapy --no-deps
```
13. confirm mamba is linked properly `ldd ./libmambapy/bindings.cpython-310-x86_64-linux-gnu.so` (it `libmamba.so.2` should be from your build directory)
14. make sure `mamba` exists now
15. (may have to mamba init shell, not sure)
16. edit your .mambarc or .condarc to add the disable_lockfile: true,
17. try to install your CellXGene with `mamba`

I just did this on my laptop and it seems to work fine... so I feel like there must be an environment conflict somewhere during linking. but not sure where.

**Comment by aghr** [comment]
@danpf 
Many thanks. I get until 9. where I see the errors listed below. In order to run 9. I had to create the mamba-dev env first and activate it: micromamba create -n mamba-dev; micromamba activate mamba-dev. I am not sure if the folder matext created in step 3 is really needed.

critical libmamba Multiple errors occured:
    Non-writable cache error.
    Subdir conda-forge/noarch not loaded!
    Subdir bioconda/noarch not loaded!
    Subdir pkgs/main/noarch not loaded!
    Subdir pkgs/r/noarch not loaded!

**Comment by danpf** [comment]
@aghr

I'm sorry I think it was very late when I wrote that.

Try:
```
micromamba install --name mamba-dev --file ../mamba/environment-dev.yml -c conda-forge
```

**Comment by jonashaag** [comment]
I think this will be fixed with the new release that adds an option to disable the lock file.
