### ISSUE TITLE
Implement `micromamba env update`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1455]
It would be nice to have a way in Micromamba to update an env from an `environment.yml`. In Mamba this works by `mamba env update -n X -f environment.yml`.

**Comment by wolfv** [comment]
I think we can use the current `micromamba update -f myenv.yml` for that.

We can add a command line option to `--prune-to-specs`.

**Comment by jonashaag** [comment]
`micro mamba update -f myenv.yml` seems to ignore `myenv.yml`.

**Comment by wolfv** [comment]
I am realizing that maybe that is the desired behavior and `micromamba install` is all we should ever need?

Let's picture some scenarios -- assuming we have a created environment. What should the ideal command line look like. We could quite easily add the following flags:

- `micromamba install -f env.yml` -> installs new packages to specs
- `micromamba install -f env.yml --update` -> installs & updates new packages according to `env.yml`
- `micromamba install -f env.yml --update --prune-to-specs` -> installs & updates new packages to specs, removes packages not in the environment but not in `env.yml`

**Comment by jonashaag** [comment]
Yes that sounds reasonable as well. What would be the role of `micromamba update` in that case? Is it just a shorthand to `install --update`?

**Comment by wolfv** [comment]
When using `install --update` we could use the `SOLVER_FLAG_INSTALL_ALSO_UPDATES` flag. It would be different from `update` because `update` doesn't install any new packages.

https://github.com/mamba-org/mamba/issues/1317

**Comment by CDTR-MattConroy** [comment]
Is there any intention to add a `--prune` option to be able to remove packages that are not specified in an environment file?

**Comment by shenker** [comment]
My understanding is that `mamba update -n myenv -f environment.yml --prune` will install new packages, update existing packages, and remove extraneous packages so that `myenv` ends up in the same state as it would be if you did `mamba env remove -n myenv && mamba create -n myenv -f environment.yml`.

It would be good for an analogous command to exist in micromamba. It would be especially convenient if this command created the environment if it didn't already exist. (E.g., after you run this command, you're guaranteed to end up with `myenv` matching the given `environment.yml` file regardless of the initial state or existence of `myenv`, and the command would get you there in the most efficient way.)

**Comment by goyalyashpal** [comment]
> --prune-to-specs
\- @ wolfv at https://github.com/mamba-org/mamba/issues/1455#issuecomment-1032754684

that is very much needed 😃 
the issue with `env create` is that it doesn't use cache and has to download all the packages again.

**Comment by GitHunter0** [comment]
What's the current best alternative to `micromamba env update -n X -f environment.yml`?

**Comment by jonashaag** [comment]
Fixed in https://github.com/mamba-org/mamba/pull/2827?

**Comment by chenzhekl** [comment]
> > --prune-to-specs
> > - @ wolfv at [#1455 (comment)](https://github.com/mamba-org/mamba/issues/1455#issuecomment-1032754684)
> 
> that is very much needed 😃 the issue with `env create` is that it doesn't use existing cache and has to download all the packages again.
> 
> combining this with #2700 issue, this pruning feature will allow to quickly remove the devt dependencies to get a lean environment back again.

`micromamba env create -f env.yaml` already reuses cache and is pretty fast to update an existing environment now.

**Comment by jjerphan** [comment]
`micromamba env update` has been implemented and improved by the following PRs:
 - https://github.com/mamba-org/mamba/pull/3396 
 - https://github.com/mamba-org/mamba/pull/2827
 - https://github.com/mamba-org/mamba/pull/3419

`{micromamba,mamba} env update -n myenv -f environment.yml --prune` (as proposed by https://github.com/mamba-org/mamba/issues/1455#issuecomment-1571088771) could potentially be implemented if this is still useful UX-wise.

Please do :+1:-react if you are interested so that this can be considered further.

**Comment by jjerphan** [comment]
I propose continuing the discussions on https://github.com/mamba-org/mamba/issues/3529.
