### ISSUE TITLE
Wrong error message with `mamba env create -f missing.yml`

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1655]
```
$ mamba env create -f foo/bar.yml
EnvironmentFileNotFound: '/private/tmp/foo/bar.yml' file not found

$ mamba env create -f foo/bar.yml -n xxx
SpecNotFound: Invalid name, try the format: user/package
```

Mamba 0.21/0.22

**Comment by unnatis07** [comment]
any help on this one?

**Comment by AdrianFreundQC** [comment]
This seems to be an upstream conda issue. I get the same output when running `conda` instead of `mamba`.

I found [this](https://github.com/conda/conda/issues/5681) very old issue in coda, which was fixed, but partially reintroduced by later changed (only when using --name). I couldn't find a current issue for conda.

The code responsible for the error is here:
https://github.com/conda/conda/blob/main/conda_env/specs/__init__.py#L20

**Comment by AdrianFreundQC** [comment]
I created an issue for conda (https://github.com/conda/conda/issues/11839) and already sent a PR to fix it (https://github.com/conda/conda/pull/11883)

**Comment by wolfv** [comment]
Thanks @AdrianFreundQC !

**Comment by AdrianFreundQC** [comment]
The fix for this was just merged in https://github.com/conda/conda/pull/11883
