### ISSUE TITLE
Corollary to conda install --revision [feature-request]

### ISSUE THREAD

**Issue by rschauner** [mamba-org/mamba#1749]
Since mamba is somewhat of a drop in replacement for conda, it would be nice if the feature mentioned at [Conda Issue #1032](https://github.com/conda/conda/issues/1032). I absolutely love using mamba, but sometimes it's hard to tell when mamba can actually be used since not all options are present.

**Comment by bilderbuchi** [comment]
duplicate of #803?

**Comment by corneliusroemer** [comment]
I _really_ need micromamba to support revisions.

Mamba just destroyed my environment by switching Python from arm -> osx-64 in my base=mamba environment and now nothing works anymore.

Conda can tell me that a previous revision exists but cannot install the previous one because, well, Python is broken. Bit of a catch-22 😬
