### ISSUE TITLE
[micromamba] micromamba create fails to install pip dependencies if prefix contains whitespace (Windows)

### ISSUE THREAD

**Issue by AtR1an** [mamba-org/mamba#1805]
I have a very simple environment.yml looking something like this:
```
name: test_env
channels:
- conda-forge
dependencies:
- python=3.9
- pip
- pip:
  - pydantic
```

Creating an environment with this yml works fine if there are no whitespaces in the prefix: `micromamba create -p "C:/tmp/micromamba_envs/env" --file "C:/tmp/environment.yml"`.
However, if I have a whitespace in the prefix: `micromamba create -p "C:/tmp/micromamba envs/env` --file "C:/tmp/environment.yml"` the installation of the pip dependencies fails with the following error:
```
Installing pip packages: typing-extensions === 4.3.0, pydantic === 1.9.1
failed to create process.
```

Note that this happens on a Windows 10 machine with micromamba 0.24.0.

**Comment by chaubold** [comment]
This issue also shows up on macOS. It seems like the path to the pip executable is not put in quotes when micromamba invokes it:

```
Installing pip packages: pydantic
/var/folders/<snip>: /Users/chaubold/Desktop/test env/bin/pip: /Users/chaubold/Desktop/test: bad interpreter: No such file or directory
critical libmamba pip failed to install packages
```

**Comment by wolfv** [comment]
that would be a very welcome contribution @chaubold !

**Comment by chaubold** [comment]
I was afraid that that would be the answer 😅 We'll see what we can do

**Comment by chaubold** [comment]
Adding quotes did not solve the issue, but the difference seems to be that `mamba` calls `pip` using the pip executable/script, whereas conda calls `python -m pip` as seen in a conda log:

```
Installing pip dependencies: - Ran pip subprocess with arguments:
['/Users/chaubold/Desktop/conda test env/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/chaubold/Desktop/condaenv.bvmf2kqm.requirements.txt']
```

Conda also warns about having spaces in environment paths, I haven't seen this warning in `mamba`. But in any case, running pip directly in an env with a space in its name does not work on UNIXes because the content of the pip executable script is:

```
#!/Users/chaubold/Desktop/conda test env/bin/python3.9
# -*- coding: utf-8 -*-
import re
import sys

from pip._internal.cli.main import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```

And spaces in a shebang are used to separate program name from arguments (see https://en.wikipedia.org/wiki/Shebang_(Unix)#Character_interpretation).

Using `python -m pip install ...` works on MacOS, we'll also test on Windows and then open a PR.

**Comment by chaubold** [comment]
@wolfv: what is your typical release cycle? How long would it take until a fix makes it into a release?

**Comment by jonashaag** [comment]
I guess you can quote the shebang. But maybe you should just not use spaces in the env name. We can make Mamba error in that case.

**Comment by chaubold** [comment]
I tried quoting the shebang manually, but that also doesn't work.

It would be great if mamba didn't bail out with an error in envs with spaces in their name, because the use case is not so uncommon: whenever a user has a space in their username and creates the env in their user folder that happens. Maybe more often on Windows than other OSes, but still often enough.

**Comment by wolfv** [comment]
I want to make a release asap. so if you get a fix in now, you'd have the fix soon.

**Comment by chaubold** [comment]
We ran into issues using the build instructions on Windows, so I went ahead and created a PR to wait for the CI pipeline to do the work for us, but it seems like somebody needs to approve the PR to build. Could you do that, please?

**Comment by jonashaag** [comment]
Bunch of related issues starting from here: https://github.com/conda/conda/issues/186

**Comment by wolfv** [comment]
Yeah, I think if you have spaces in the path to the environments, you'll always be in a world of pain. But the fix might make it a little bit better.

**Comment by chaubold** [comment]
Thanks for the pointer @jonashaag! Yeah that's really nasty. I'd prefer if file systems didn't allow spaces in paths, but that is a different discussion 😅

**Comment by wolfv** [comment]
Closing as this was merged

**Comment by chaubold** [comment]
The issue was reintroduced with #1828 unfortunately.

**Comment by wolfv** [comment]
Mayb

**Comment by wolfv** [comment]
*Maybe you can give it another go and add a test :) That would also have caught the issue on Windows. 
Unfortunately a lot of people are depending on micromamba in their CI pipelines nowadays, so we had to get a fix out of the door quickly.

**Comment by Klaim** [comment]
Hopefully #1838 should fix that issue. Reviews welcome :)
