### ISSUE TITLE
Having `micromamba` in PATH conflicts with `micromamba` shell function

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#1895]
Investigate this https://github.com/mamba-org/mamba/blob/7a4f488568d71335f807b280719c2a03f39651ff/.github/workflows/test_micro.mamba.pm.yml#L42-L44

**Comment by pavelzw** [comment]
This seems to be special for the GitHub Actions `ubuntu-latest` image. On a regular Ubuntu installation like the [Ubuntu docker container](https://hub.docker.com/_/ubuntu), `$HOME/.local/bin` is not in `$PATH`. 

Though the semantics of the `bin` folder usually implies that this folder *should* be in path imo. Maybe putting the `micromamba` executable in `$HOME/micromamba/bin/micromamba` would be better?

**Comment by jonashaag** [comment]
IMO it doesn’t matter what’s the exact folder. Micromamba should work fine with the binary in the PATH, otherwise it’s a bug IMO.

**Comment by AntoinePrv** [comment]
> This function would somehow need to be integrated into the micromamba executable... This seems like a kind of long journey.

The way I understand it is that it is not possible. When executed, `micromamba` is a sub-process and cannot change the user's env (`PATH`, `CFLAGS`...) during activation.

> Micromamba should work fine with the binary in the PATH, otherwise it’s a bug IMO.

I agree, I have `micromamba` in `PATH` and everything works fine. It is even necessary for scripts (*e.g.* using `micromamba run`) that do not have access to the function.

**Comment by pavelzw** [comment]
> I agree, I have micromamba in PATH and everything works fine.

@AntoinePrv have you got an idea why [this](https://github.com/pavelzw/ci-test/actions/runs/3021562222) fails then (it belongs to [this](https://github.com/pavelzw/ci-test/blob/micromamba-path-broken/.github/workflows/ci.yml) CI file)? I thought it has something to do with the `micromamba` executable being in `PATH`...

**Comment by pavelzw** [comment]
> It is even necessary for scripts (e.g. using micromamba run) that do not have access to the function.

Are you saying that `micromamba run` only works if it is in `PATH` and not if *only* [this](https://github.com/mamba-org/mamba/issues/1895#issuecomment-1234531093) function definition is sourced?

**Comment by AntoinePrv** [comment]
> Are you saying that `micromamba run` only works if it is in `PATH` and not if _only_ [this](https://github.com/mamba-org/mamba/issues/1895#issuecomment-1234531093) function definition is sourced?

No I was saying if you want to use `micromamba` *from another program*, you can sometimes not activate (because you don't always have the function), in that case `micromamba run` is useful.
But you can absolutely use `micromamba run` *from your shell* if you only have the function.

> @AntoinePrv have you got an idea why [this](https://github.com/pavelzw/ci-test/actions/runs/3021562222) fails then (it belongs to [this](https://github.com/pavelzw/ci-test/blob/micromamba-path-broken/.github/workflows/ci.yml) CI file)? I thought it has something to do with the `micromamba` executable being in `PATH`...

I'm not so keen on debugging CI pipelines. I would recommend using https://github.com/mamba-org/provision-with-micromamba for a well-tested solution.

**Comment by pavelzw** [comment]
> No I was saying if you want to use micromamba from another program, you can sometimes not activate (because you don't always have the function), in that case micromamba run is useful.

Ah okay, makes sense :)

> Overall I think we are getting off tracks from OP original intend.

No, the CI run that I posted is exactly a minimal version of what is described (by me) in the comment referenced by Jonas. The CI run is trying to emulate how the installation with the [micro.mamba.pm installation script](http://micro.mamba.pm/install.sh) should work on a regular Ubuntu machine where the micromamba executable is in `PATH`. I haven't tested it in a regular Ubuntu environment outside the GH Actions Ubuntu image, though. 

It is described in further detail in #1848 (sorry for the wall of text there 😅).

**Comment by AntoinePrv** [comment]
Ha, sorry for the misunderstanding.

**Comment by jonashaag** [comment]
@pavelzw I may have found the issue (or another one): This piece of code that I wrote checks that the prefix is a legitimate prefix, and I think it misses a case: When using the `curl | bash` installation method, only `prefix/etc/profile.d` is created (if using bash), but we miss this case here: https://github.com/mamba-org/mamba/blob/02e4385d2ff5158a70ad86c295f405878f21e2d9/libmamba/src/api/configuration.cpp#L540-L546 We should add another case that looks for `prefix / "etc"`. Maybe we can come up with a more robust way of marking a directory a Mamba prefix, like a `.mamba-prefix` file or something.

**Comment by pavelzw** [comment]
Okay so I did some further digging and apparently, what I stated in the comment at the top of this thread is not true 😅

I thought that `$PATH` got overridden because when I used mxschmitt/action-tmate to do debugging on the remote machine, it actually didn't read from the `~/.bashrc` file when connecting to the shell :/

So we can remove the `PATH` modifying block, it has nothing to do with this...

@jonashaag 
This `Directory exists, is not empty and not a conda prefix.` error is not because some directories are not created correctly but because `$MAMBA_ROOT_PREFIX` is not set when not sourcing the `.bashrc`. That's what happened in the CI run that I referenced earlier.

Everything *should* work when just executing `micromamba` with `bash -i`, I'll create a PR that simplifies the "fixes" that I've done to the `test_micro.mamba.pm.yml`.

**Comment by jonashaag** [comment]
> Having `micromamba` in `PATH` doesn't break anything.

That's great news :)

> because `$MAMBA_ROOT_PREFIX` is not set when not sourcing the `.bashrc`

Yes and no; it's true that this particular piece of code that I quoted is only executed if `$MAMBA_ROOT_PREFIX` is empty. But Micromamba should still work if you have your prefix at the default location, that's what this piece of code is checking for in the first place. It doesn't though because it doesn't recognise a folder with only a `etc/` subfolder as a valid prefix, which is wrong.
