### ISSUE TITLE
How to remove Micromamba from my Mac

### ISSUE THREAD

**Issue by dotty37** [mamba-org/mamba#1947]
I dont want Mamba or Micromamba on my Mac.
How do you remove them completely?
Files, folders, PATH, etc etc etc
Where are the instructions for that?

**Comment by wolfv** [comment]
Hi @dotty37 you can remove it by removing the `micromamba` file, the `~/micromamba` folder and editing your `.bashrc` file (or `.zshrc`) and removing the code added by `shell init` there (it's easy to spot because it is surrounded by `>>> mamba init <<<` fences.

There is also a `micromamba shell deinit` option if you are on a very recent version of `micromamba`.

**Comment by agilebean** [comment]
> There is also a `micromamba shell deinit` option if you are on a very recent version of `micromamba`.

That works very well cleaning all configs but - you still have to remove the micromamba folder manually
