### ISSUE TITLE
Backport better support for prefixes with spaces

### ISSUE THREAD

**Issue by wolfv** [mamba-org/mamba#1970]
@jaimergp made a neat PR to fix things in conda: https://github.com/conda/conda/pull/11676/files

**Comment by jaimergp** [comment]
Be aware of this regression: https://github.com/conda/conda/issues/11885

We have a fix in the way, so just wait a bit while we implement it :D

**Comment by jaimergp** [comment]
This was finally tackled with a conda-specific workaround (https://github.com/conda/conda/pull/12043) so I think you can implement it safely in `micromamba` (since it needs no shebang itself).

**Comment by wolfv** [comment]
So you just use `/usr/bin/env` if there is a space?

**Comment by jaimergp** [comment]
Only for the `$BASE_PREFIX/bin/conda[-env]` entry points created by `conda init` (this is restoring the old behavior). Otherwise `$PS1` is dropped in CentOS7.

This approach won't allow people to run `$BASE_PREFIX/bin/conda` from non-initialized activations _if_ $BASE_PREFIX contains spaces. The most robust workaround is in https://github.com/conda/conda/pull/11995, but it's a complete overhaul.

**Comment by wolfv** [comment]
I made a PR: #2211 let me know what you think :)

**Comment by jaimergp** [comment]
This can be closed now, right?
