### ISSUE TITLE
Implement `[md5=...]` package specifier

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2053]
Mamba does not support specifying `md5/sha256=`:

```
$ mamba install 'pkg=...[md5=...]'
CondaValueError: invalid package specification: pkg=...[md5=...]

$ micromamba install 'pkg=...[md5=...]'
# Will just ignore the md5= restriction.
```

**Comment by jonashaag** [comment]
It's not obvious to me how to add this:

- In libsolv? So far libsolv only understands `name`, `version`, and `build`.
- As some sort of pre/post filter in libmamba?

@wolfv @AntoinePrv

**Comment by AntoinePrv** [comment]
The way it is done for channel-specific jobs is a filtering done on Mamba side, because it is not supported directly by libsolv, one could do the same here.

I'm not a big fan of having the version/dependency specs in libsolv, exactly for this sort of reason. A goal of mine through this refactoring of the solver API is to get back those functions in Mamba, and somehow pass them to libsolv as a callback.
Then this can all be handled through the `MatchSpec` class, without custom solver logic everywhere.

@jonashaag what is your priority on this?

**Comment by jonashaag** [comment]
Thanks for the insights. I think we're fine with using the build string for now, but would definitely want to have a strict check in the future.

**Comment by AntoinePrv** [comment]
If it is not too urgent, it could be done as part of the #2302 plan.

**Comment by wolfv** [comment]
yeah this would be very nice. `libsolv` knows about the md5 / sha256 hashes (they are stored in the Solvable), but one would indeed have to add that as additional "SOLVABLE_ONE_OF" queue (although selecting might be easy).

The md5 hash is stored as `SOLVABLE_PKGID` (https://github.com/mamba-org/mamba/blob/b46dbbf1b167db78c11a6e6c5348ebc6c6304f1f/libmamba/src/core/package_info.cpp#LL141C43-L141C57) and the sha256 sum is stored as `SOLVABLE_CHECKSUM`.

I think it could be done with libsolv today but yeah, it would be much nicer to have the proper `MatchSpec` support that @AntoinePrv mentions.

**Comment by jonashaag** [comment]
With the lastest Mamba, `[md5=...]` is ignored for both Micromamba and Mamba

**Comment by jonashaag** [comment]
Works with Conda.

**Comment by AntoinePrv** [comment]
> With the lastest Mamba, [md5=...] is ignored for both Micromamba and Mamba

@jonashaag yes that is still the case.

As mention, my preference is to implement this as part of a fully-featured `MatchSpec` class (we'll have to see how we plug it into libsolv but I have an idea :crossed_fingers:). Otherwise we keep accumulating hacks.

If this is high priority, we can totally implement Wolf's suggestion in the meantime.

**Comment by jonashaag** [comment]
Not a high priority for us right now.
