### ISSUE TITLE
Collaborate on terminal UI

### ISSUE THREAD

**Issue by certik** [mamba-org/mamba#222]
I noticed you have currently hand written some basic terminal UI, such as a [progress bar](https://github.com/QuantStack/mamba/blob/a56dc6f8f5a8c209faa7c2c2fc494465b33c6f63/src/output.cpp). Would you be interested in extracting it to a separate library so that I can use it on other projects ([LFortran](https://lfortran.org))? I have written this library:

https://github.com/certik/terminal/

At the end of the README I have done comprehensive research about similar such libraries: https://github.com/certik/terminal/#similar-projects

For LFortran I also need a replacement for readline / prompt / prompt_toolkit (with multiline editing). You probably don't need that for mamba (although you do for xeus?), but you still need rich drawing on screen with unicode (!) that works in all terminals including Windows.  Starting with progress bars --- I need those too. Would you be interested in extracting those to a separate project and collaborating on this?

**Comment by wolfv** [comment]
nice! definitely interested. I myself ported the progress bars from https://github.com/p-ranav/indicators . to be honest I ported them because they were not exactly doing what I wanted and I had to move quickly and the library was a little overly complicated.

But I saw some functionality in your lib that I reimplemented here and that would definitely be well suited for factoring out.

E.g. I have all this code for cursor movement (which I ported from a go library): https://github.com/QuantStack/mamba/blob/master/include/output.hpp#L17

One other thing that we tried to do is that when we have multiple progress bars and output at the same time, to make sure that the output is not overwritten by the progress bars. That's why all progress bars are part of a `Console` singleton that should keep track of the state of the output.

We also have some lightweight logging that can be globally turned on or off.

**Comment by wolfv** [comment]
btw one more thing: we have a lightweight tree writer and a lightweight table writer as part of mamba itself right now.

I think both could be independent headers in terminal if you want them and we could make them slightly more customizable.

https://github.com/QuantStack/mamba/blob/245f7736acda3f72d0e6993e88309e494b013e63/src/query.cpp#L17-L123

**Comment by certik** [comment]
Yes, essentially I would like to extract anything related to terminal handling into a standalone library, that I can use in all my projects. Yes, essentially it's a "ncurses" replacement, but better / simpler, and that actually works on Windows natively.

Yes, cursor movement and also you need to keep track of what is on the screen and then do an efficient diff. 

And then in addition, the most common widgets, such as a progress bar, table, and other things. I need all that for LFortran also.

And the multiline prompt, while not needed for Mamba, would come very handy for xeus-cling I think, to have a pure C++ interactive environment (my understanding is that currently you have to use IPython/Jupyter to get the interactive prompt on the command line).
