### ISSUE TITLE
Micromamba can't install local `.tar.bz2` package

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/mamba#2291]
See https://github.com/mamba-org/mamba/issues/2238#issuecomment-1430180999. Not sure if it's the same bug.

**Comment by jonashaag** [comment]
This is still present in 1.4.9

**Comment by delsner** [comment]
I would take a look at this, but let's align first on what is (still) not working and what the expected behaviour would be.

## Status Quo

Tested on `osx-arm64`.

**1.x**

```
❯ ./build/1.x/micromamba/micromamba install -n empty /tmp/osx-arm64/zstandard-0.19.0-py39h02fc5c5_0.tar.bz2 -c conda-forge/osx-arm64
conda-forge/osx-arm64                                       Using cache
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
file:///tmp/osx-arm64 (check zst)                  Checked  0.0s
file:///tmp/noarch (check zst)                     Checked  0.0s
file:///tmp/osx-arm64                               ??.?MB @  ??.?MB/s 0 failed  0.0s
critical libmamba Multiple errors occured:
    Download error (37) Couldn't read a file:// file [file:///tmp/noarch/repodata.json]
    Couldn't open file /tmp/noarch/repodata.json
    Subdir file:///tmp/noarch not loaded!
```

It seems like this doesn't work because the `noarch/repodata.json` file doesn't exist, i.e., a certainy directory structure is expected.

**main**

```
❯ ./build/main/micromamba/micromamba install -n empty /tmp/osx-arm64/zstandard-0.19.0-py39h02fc5c5_0.tar.bz2 -c conda-forge/osx-arm64
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
conda-forge/osx-arm64                                       Using cache
error    libmamba Could not solve for environment specs
    The following package could not be installed
    └─ zstandard 0.19.0 py39h02fc5c5_0 does not exist (perhaps a typo or a missing channel).
critical libmamba Could not solve for environment specs
```

## Expected Behavior

I assume `micromamba` should align with `conda` (`23.11.0`) which installs the package just fine and adds the `channel` `file:///tmp/osx-arm64` in `conda-meta/zstandard....json`. If the `tar.bz2` file is located in `/tmp`, the `channel` is set to `<unknown>`.

Is that correct @jonashaag?

**Comment by jonashaag** [comment]
Not sure about adding the channel to `conda-meta`, but it's probably a good thing to do whatever Conda does.

Fixing on `main` only is fine. `1.x` will get no new features. If it's very easy to back port that would be nice but not necessary.

**Comment by AntoinePrv** [comment]
@edemattos this PR will ship in v2 which is still in alpha (we'll make a new alpha release soon).

> Alternatively, is there a way to point micromamba-version in setup-micromamba to the main branch?

Alpha builds are in a separate channels. At the current time I don't believe you can, but it should not be too hard to do.
