### ISSUE TITLE
Improvement: sort packages to be linked alphabetically

### ISSUE THREAD

**Issue by tschuelia** [mamba-org/mamba#2957]
See title, e.g. 

```
Package                               Version  Build               Channel           Size
─────────────────────────────────────────────────────────────────────────────────────────────
  Install:
─────────────────────────────────────────────────────────────────────────────────────────────

  + xz                                    5.2.6  h57fd34a_0          conda-forge     Cached
  + libexpat                              2.5.0  hb7217d7_1          conda-forge     Cached
  + libzlib                              1.2.13  h53f4e23_5          conda-forge     Cached
  + python_abi                             3.11  4_cp311             conda-forge        6kB
  + ncurses                                 6.4  h463b476_2          conda-forge     Cached
  + bzip2                                 1.0.8  h3422bc3_4          conda-forge     Cached
  + libffi                                3.4.2  h3422bc3_5          conda-forge     Cached
  + ca-certificates                   2023.7.22  hf0a4a13_0          conda-forge      150kB
  + libcxx                               16.0.6  h4653b0c_0          conda-forge     Cached
  + reproc                         14.2.4.post0  h93a5062_1          conda-forge       32kB
  + libiconv                               1.17  he4db4b2_0          conda-forge        1MB
  + lzo                                    2.10  h642e427_1000       conda-forge      157kB
  + icu                                    73.2  hc8870d7_0          conda-forge       12MB
[...]
```

It's easier to see which packages will be installed if the names are sorted alphabetically :-)

**Comment by AntoinePrv** [comment]
We could sort the output but the packages need to be sorted topologically depending on their dependencies, otherwise some linking fail (e.g. python packages without python).

**Comment by tschuelia** [comment]
Yes sorting the output is what I meant, sorry for not stating this more clearly :-)

**Comment by valeriupredoi** [comment]
hey guys, let me just first off thank you for the wonderful work you folks are doing on `mamba` - we've been happy users of it since a few years now, massive performance change from the good ole slow conda solver :beer: Now, to add to what the OP mentions, it'd be really really great if you could make sure the output is in alphabetical order (like it used to be, we're seeing the list of packages not being in alphabetical order since mamba==1.5.5) - it helps a lot with looking up environment changes especially in CI runs, see how jumbled the pkgs list is now

![mamba-stdout](https://github.com/mamba-org/mamba/assets/28983971/5ea86b0c-0ab3-46a7-b919-1fc9d2d9e94b)

Many thanks in advance! :beer:

**Comment by jonashaag** [comment]
This is an open source project, feel free to contribute

**Comment by valeriupredoi** [comment]
brilliant, very many thanks, folks :beer:
