### ISSUE TITLE
Fail on GHA/Windows: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by maartenbreddels** [mamba-org/mamba#408]
seeing this here:
https://github.com/vaexio/vaex/pull/885/checks?check_run_id=878167514

Seems related to #249 but downgrading libssh2 didn't help.

**Comment by wolfv** [comment]
hmm annoying. unfortunately I can't see the run because the link from above just jumps to the latest build.

**Comment by wolfv** [comment]
@maartenbreddels I am poking in the dark, but just wondering -- could it be possible that you were using a Python from defaults?

We had a similar error with OS X just recently #409 and I am pretty sure that it's because defaults and conda-forge are not necessarily binary compatible.

Enjoy your holiday!

**Comment by wolfv** [comment]
haven't heard about this in a while

**Comment by maartenbreddels** [comment]
Yeah, seems to be working now

(from mobile phone)

**Comment by nvaytet** [comment]
I am seeing this as well on Azure: https://dev.azure.com/scipp/scipp/_build/results?buildId=6509&view=logs&jobId=63453d53-15fd-5495-e319-bb80e05c85cc&j=d5c58a2e-1ae4-501e-e421-b21c980eb30a&t=7c4cba8d-b07c-5019-f73d-89e315067969

I tried installing python from conda forge, but it doesn't seem to help: https://dev.azure.com/scipp/scipp/_build/results?buildId=6627&view=logs&j=d5c58a2e-1ae4-501e-e421-b21c980eb30a&t=267779b4-482a-5da4-8530-4fc5618f6741&l=54
