### ISSUE TITLE
mamba env update doesn't accept a url

### ISSUE THREAD

**Issue by dhirschfeld** [mamba-org/mamba#519]
```
$ mamba env update --file https://gist.githubusercontent.com/dhirschfeld/6a56e6c7c32551e013291950ec0da020/raw/e336bac3e24b081fc7b221beacc7df5a7e849390/environment.yml

EnvironmentFileNotFound: '/home/user/https:/gist.githubusercontent.com/dhirschfeld/6a56e6c7c32551e013291950ec0da020/raw/e336bac3e24b081fc7b221beacc7df5a7e849390/environment.yml' file not found
```

**Comment by dhirschfeld** [comment]
mamba (0.5.1) on linux

**Comment by martinRenou** [comment]
This happens with `conda env` as well, using `conda 4.8.5`. If there is a conda version that supports this notation I suspect installing this conda version would actually fix this notation support with mamba as well (because mamba relies on conda for fetching and reading the file if I understand correctly).

**Comment by dhirschfeld** [comment]
Ah true. `{conda|mamba} env create --file https://...` *does* work so I guess it's just a missing corner case in `conda`. I'll close this as, if it should be fixed, it should probably be fixed upstream...

**Comment by martinRenou** [comment]
If it's fixed upstream it should work with mamba :)

**Comment by wolfv** [comment]
this particular part of conda is quite a mess... there are two different programs (`create` vs `env create`) that do similar things.

**Comment by dhirschfeld** [comment]
> *this particular part of conda is quite a mess...*

yup 😬
