### ISSUE TITLE
Future of mamba

### ISSUE THREAD

**Issue by xhochy** [mamba-org/mamba#54]
There has been the word out that you talked with Anaconda about how the mamba changes could be used in `conda` itself instead of having `mamba` on-top. What has been the outcome of this? Will we see still a future `mamba` that patches some speedups on top or is all work going into `conda`?

**Comment by wolfv** [comment]
Hi @xhochy the future has still not been decided! At scipy and with Anaconda, we could not find a straight forward way to integrate conda with mamba parts yet, and on top of that I have been really busy with another client.
For that reason, I haven't really been able to do much more work besides some maintenance here and there on mamba. But I think some people are using it from time to time (myself included) and haven't reported that many problems so that's already quite cool.

One of the big outstanding tasks is to change the sorting order of non-explicit specs to maximize overall versions (at least in a conda-compat mode) because conda doesn't respect the build number for non-explicit specs and optimizes for overall versions which leads to environments that have slightly different versions of some dependencies than what you get from conda. (Especially due to the 100X build numbers from the big compiler migration).

The other thing is updating all packages "touched" by dependencies (right now if you do `mamba update mypackage` it tries to only update `mypackage` and not all dependents if not necessary which is also different from conda).

If we have those two things we can say that we're extremely close in compatibility ;)

On top of that we're interested in exploring `librepo` (https://github.com/rpm-software-management/librepo) for package and repository data download which would be pretty neat if that library could handle all these things for us. It would probably require a chunk of work again to make it cross-platform though! And we might try to make some more tooling from `libsolv` available on the command line, for example, to inspect reverse dependencies (`--whatrequires` in dnf, or `rdepends` in apt) and other such things (c.f. with `repoquery` commands in `dnf`). 

If the :stars: align we might be able to allocate some time to this next year!

**Comment by xhochy** [comment]
Thanks for sharing these points!

**Comment by Conan-Kudo** [comment]
I'm certainly excited to see a new potential user of librepo! The architecture of the library should make it fairly straightforward to support your use-case. :)

**Comment by dmach** [comment]
> On top of that we're interested in exploring `librepo` (https://github.com/rpm-software-management/librepo) for package and repository data download which would be pretty neat if that library could handle all these things for us. It would probably require a chunk of work again to make it cross-platform though! And we might try to make some more tooling from `libsolv` available on the command line, for example, to inspect reverse dependencies (`--whatrequires` in dnf, or `rdepends` in apt) and other such things (c.f. with `repoquery` commands in `dnf`).

librepo is quite low-level and not exactly easy to use.
You could also look into using libdnf (if it does the job for you) and is not too heavyweight.
If you prefer to use librepo and something is not working for you, could you open us a ticket with your use cases and suggestions? In long-term, we'd like to improve librepo or even merge it into libdnf and we need to know as may user scenarios as possible in order to preserve the right functionality or change it in the right way.

**Comment by Conan-Kudo** [comment]
@dmach I think for mamba to use libdnf, it'd need to be possible for it to operate on Conda repositories. While libsolv _does_ support processing them, librepo still needs to know how to download them for libdnf to leverage them well.

**Comment by wolfv** [comment]
Hi @Conan-Kudo and @dmach thanks for dropping by! Cool to hear from you :)

What I am looking for with regards to librepo is ideally a tool which I can give a bunch of URLs with potential mirrors and have it download them as fast, parallel and stable as possible (and produce nice output like dnf does). I haven't looked too deeply into librepo, but the sales pitch sounded like it might be the right tool...

**Comment by wolfv** [comment]
Note one other challenge is that mamba needs to run on Windows and OS X as well ... especially Windows support is sometimes hard to achieve. As far as I can see libdnf is pretty tied to rpm's and possibly Linux? I am curious though if the idea of delta-rpms could be used with conda as well ... but that might be quite far out.

**Comment by Conan-Kudo** [comment]
At least on the macOS front, that's something I'm happy to help with and am quite interested in getting working. I've got my own effort to bring a fully functional DNF stack to macOS to use as a package manager for software instead of Homebrew, so portability issues for macOS are of interest to me.

For Windows, I'm not sure where we are on portability, but if we want to move towards improving that, I'm not terribly opposed to this. It's easy enough for us to add test builds for it to CI with MinGW builds of everything (once we can have working builds), at least...

**Comment by wolfv** [comment]
@Conan-Kudo great! That would be cool. You could also always try out conda (or mamba) for your package manager needs on OS X, it's not that much worse than dnf ;)

For libsolv it was not _that_ hard to get Windows support, but something that involves more networking might be more difficult. I think first we'll try librepo for Linux, then move on to make it compatible with the other two. I also looked a bit at libdnf and it looks like very nice and clean C++. We might borrow some abstractions from there.

**Comment by wolfv** [comment]
@Conan-Kudo just curious if your experiments regarding OS X support for librepo ever got anywhere?

**Comment by hadim** [comment]
Is mamba going to be integrated within conda at some point? Have you done any progress on that side?

**Comment by wolfv** [comment]
Hi Hadim, 

we haven't made any progress on that part for the moment. Not tightly integrating with upstream allows us to move somewhat faster right now :)

**Comment by wolfv** [comment]
Most of the promises here became true this year :rocket: 

Going to close this. Will publish a blog post with ideas for next year at some point.

**Comment by hadim** [comment]
Thanks, @wolfv. mamba is a fantastic tool that I now use as a full replacement of conda. This project is gold!
