### ISSUE TITLE
Linking phase error

### ISSUE THREAD

**Issue by adriendelsalle** [mamba-org/mamba#607]
Hi!

I get a linking error when installing `cosapp` from conda-forge, during the compiling stage (generation of `.pyc` files).
In fact it comes from a `.py` file that is indeed a `jinja2` template. It should be fixed on the `cosapp` project repo.

``` shell

Linking cosapp-0.11.2-py_0
*** Error compiling 'Lib\\site-packages\\cosapp\\tools\\templates\\pythonfmu.py'...
  File "Lib\site-packages\cosapp\tools\templates\pythonfmu.py", line 5
    from cosapp.drivers import {{ driver }}, NonLinearSolver
                               ^
SyntaxError: invalid syntax
```

But I have 2 questions about that :
- Is this error interrupt the linking process or not (for all the packages but also for the current one)?
- Should we raise a warning instead of an error since the generation of `.pyc` is not mandatory but just a speed-up to avoid generation at runtime?

**Comment by wolfv** [comment]
hey, 

when you install a noarch package, conda / mamba compiles all `.py` files to `.pyc` files, and adds them to the list of installed files (so that when you remove the package it will remove the `.pyc` files as well. 

So if this compilation fails for a file or two, it should not matter and linking should just continue... does it continue? 

It woudl be good to investigate if we're recording the right metadata in `conda-meta/cosapp-0.11.2-py_0.json`, and compare it to what conda records in the case of a failed compilation here.

**Comment by adriendelsalle** [comment]
Hi @wolfv. Thanks for your reply!

It looks like the env is not broken and working as expected. It should be confirmed by a more intensive use.
Since we can see others packages "linking", they should be fine.

Why doing this generation only for noarch packages? Platform specific packages could also contain `.py` files that we would like to "compile". I am missing a point?

What is your opinion about rising a warning instead an error?

**Comment by wolfv** [comment]
The error doesn't come from us, but it's a Python error. So may be hard to catch.

Platform specific python packages have the pyc files inside the package already
