### ISSUE TITLE
Usage question: `repoquery` for `environment.yml` that fails to resolve.

### ISSUE THREAD

**Issue by trendelkampschroer** [mamba-org/mamba#638]
Hi, thanks a lot for creating `mamba` and making it freely available.

I have a usage question regarding the `repoquery` command.

My current understanding is that I can use the `repoquery` command only on dependencies in the current (mamba/conda) environment, i.e. those that have already been successfully resolved.

I have an `environment.yml` file which I cannot resolve. I'd like to use `repoquery` on the dependency which cannot be resolved when I run `mamba env create` on the given `environment.yml` file. 

Is this possible?

Thanks a lot!

**Comment by wolfv** [comment]
Hi, it's possible to use `repoquery` with channels.

For example: `mamba repoquery depends xtensor -c conda-forge`

or `mamba repoquery whoneeds xtensor -c conda-forge`

please note that the results in the depends query are basically just random versions since no full solve is performed. there is a seperate issue for that https://github.com/mamba-org/mamba/issues/618
