### ISSUE TITLE
RuntimeError: Multi-download failed

### ISSUE THREAD

**Issue by maartenbreddels** [mamba-org/mamba#663]
Seeing this in CI https://github.com/vaexio/vaex/pull/1181/checks?check_run_id=1761942388 withmamba-0.7.10

**Comment by xhochy** [comment]
You have non-CDN channels in your `conda` configuration:

```
https://conda.anaconda.org/msys2/osx-64
https://conda.anaconda.org/msys2/noarch
https://conda.anaconda.org/anaconda/osx-64
https://conda.anaconda.org/anaconda/noarch
```

They all error with HTTP 500 currently as anaconda.org is down since at least the European morning. `mamba` should print a better error for this somehow.

@maartenbreddels Specifically for `vaex`, you shouldn't need these channels anymore. Everything on all OSes should nowadays be included in conda-forge, so you could just get rid of them.

**Comment by wolfv** [comment]
Thanks @xhochy! I think the problem has been fixed now on Anaconda side (https://gitter.im/conda/conda?at=600ed542cae490555f6862cd)

**Comment by maartenbreddels** [comment]
Thanks, both, and sorry for the noise since this was not mamba related (except maybe a better error), cheers!
