### ISSUE TITLE
Bad solve results in openssl error?

### ISSUE THREAD

**Issue by krishanj20** [mamba-org/mamba#769]
Hi,

sometimes when resolving environments using mamba, when theres a bad solve I get the error
```
Encountered problems while solving.
Problem: nothing provides openssl >=1.1.1,<1.1.2.0a0 needed by python-2.7.15-h9bab390_2

```
Now this is even though I have `python=3.8` as a constraint, so why is it looking for something required by 2.7.15?

**Comment by wolfv** [comment]
that happens when the solver goes down a "bad branch" to try to find a solution. You can inspect that with the `-vvv` flags that will show you everything libsolv is doing.

I am going to close this because there is no "openssl error" here (just bad solver messaging). We already have a bunch of open issues wrt non-ideal solver messages. We would love to improve the solver messaging further but that probably requires some intense work, and for now I think we want to fix the obvious things first.
