### ISSUE TITLE
micromamba should have env command

### ISSUE THREAD

**Issue by antonkulaga** [mamba-org/mamba#781]
Not having micromamba env command is very inconvenient as I cannot list all avaliable environments.

**Comment by wolfv** [comment]
I am expanding a bit background info on this issue:

conda has the `conda env list` command that lists all available environments. This information is usually stored in an `environments.txt` file in the `~/.conda/environments.txt` file.

We already write to the `environments.txt` file IIRC, but we currently have no CLI option to read it and show it to the micromamba users. 

To solve this issue, we need to add a new command to micromamba so that one can do `micromamba env list`.

**Comment by antonkulaga** [comment]
I think env list works now, so I close
