### ISSUE TITLE
Configs not read from rc file

### ISSUE THREAD

**Issue by marimeireles** [mamba-org/mamba#966]
Here's a description of the problem:
I have an rc file under `home/user/.rcfile`. The contents of my file are:

```
channels:
  - a
  - b
json: true
```

If I use the command `./micromamba config list -a --rc-file=/home/user/.rcfile` I get the following result:

```
root_prefix: /home/user/miniconda3
create_base: false
target_prefix: /home/user/miniconda3
use_target_prefix_fallback: true
target_prefix_checks: 14
env_name: ""
platform: linux-64
spec_file_env_name: ""
specs: ~
experimental: false
channels: ~
channel_alias: https://conda.anaconda.org
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
override_channels_enabled: true
cacert_path: ""
local_repodata_ttl: 1
offline: false
ssl_no_revoke: false
ssl_verify: /etc/ssl/certs/ca-certificates.crt
channel_priority: flexible
explicit_install: false
file_specs: ~
no_pin: false
pinned_packages: ~
retry_clean_cache: false
allow_softlinks: false
always_copy: false
always_softlink: false
safety_checks: warn
extra_safety_checks: false
always_yes: false
auto_activate_base: false
dry_run: false
json: false
show_banner: false
show_all_configs: true
show_config_descriptions: false
show_config_groups: false
show_config_long_descriptions: false
show_config_sources: false
show_config_values: false
quiet: false
verbose: "\x00"
prepend_map:
  - ""
append_map:
  - ""
remove_key: ""
set_value: ~
get_value: ""
rc_file:
  - /home/user/.rcfile
no_rc: false
no_env: false
shell_type: ""
shell_stack: false
shell_action: ""
shell_prefix: ""
override_channels: false
strict_channel_priority: false
no_channel_priority: false
update_all: false
remove_all: false
list_regex: ""
clean_all: false
clean_index_cache: false
clean_packages: false
clean_tarballs: false
config_set_file_path: ""
constructor_prefix: ""
constructor_extract_conda_pkgs: false
constructor_extract_tarball: false
```
As you can see the `json` value is wrong and also the `channels`, but the `rc_file` value is correct.

I don't know where this is drawing the information from, it's not from my default files because the content of my `.condarc` for example is:

```
channels:
  - defaults
json: false
```

**Comment by adriendelsalle** [comment]
Thanks @marimeireles for opening this issue.
This is due to https://github.com/mamba-org/mamba/blob/a280e3e498811d588add6fddf405986b5508dff2/src/api/configuration.cpp#L939

When loading the configuration, configurables have no preferred order except when :
- others configurables are declared needed, they will be computed *before*
- others configurables are declared implying, they will be computed *right after* 
The second one should be maybe removed at some point, because it doesn't translate a dependency.

Following this logic, any configurable that is rc configurable is automatically tagged as needing `rc_file` because it's value can be modified there.
Same for en var configurables, needing `no_env` that may prevent loading for this kind of source.

To prevent circular dependencies while loading we had to hardcode what config is loading first.
As documented in the code:
- target_prefix (env configurable) -> no_env (rc configurable) -> rc_file -> target_prefix
- target_prefix -> always_yes (rc configurable) -> rc_file -> target_prefix
     
Another consideration was to prevent logs to show before the banner, with is not nice. The banner also needs to be silented when using json output, which is rc configurable.
Loading rc configs produces some logs because of possibles not found files etc. And not logging that is also not nice.

I guess the best solution would be to store those logs and only show them after displaying the banner.
That's a bit tricky and we also have to take care of flushing those messages if anything goes wrong during early stages of loading, to not lose this important debug info.
I'll try something on that.

**Comment by adriendelsalle** [comment]
By the way `home/user/.rcfile` is not a valid rc file name, please see https://github.com/mamba-org/mamba/blob/a280e3e498811d588add6fddf405986b5508dff2/src/api/configuration.cpp#L1212

**Comment by adriendelsalle** [comment]
> I was just asking myself where this information is coming from.

Those are default values:
- channels: ~
- json: false

If you try `-s` to also display config sources, it should be printed as yaml comments.

> Sorry, I don't get why not. What if the path is /home/user? You're just getting the name of the file in a given path no? fs::path(file).filename()

Ah it's just we handle legacy use case where you can pass a directory and expect that any file looking like an rc file will be picked. So we added this check that the filename matches either `.condarc` or `.mambarc`, or ends with `.yml`/`.yaml` extensions!

But it's maybe not relevant in the case where we pass explicitly the file path.

**Comment by marimeireles** [comment]
Alriiighty, now I got it. Thanks Adrien!

**Comment by RayPS** [comment]
micromamba ignoring my config.
The content of my `.condarc`:
```
channels: [conda-forge]
changeps1: false
auto_activate_base: true
```
This config is working with `mamba` but not `micromamba`.

If I run `micromamba config list | grep 'changeps1'` it will return no result.

**Comment by wolfv** [comment]
@RayPS yes, we haven't implemented that setting yet. A PR would be wonderful!
